/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todos los vehículos */
        get: operations["VehicleController_findAll"];
        put?: never;
        /** Crear un vehículo (bus) */
        post: operations["VehicleController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un vehículo por id */
        get: operations["VehicleController_findOne"];
        put?: never;
        post?: never;
        /** Eliminar un vehículo */
        delete: operations["VehicleController_remove"];
        options?: never;
        head?: never;
        /** Actualizar parcialmente un vehículo */
        patch: operations["VehicleController_update"];
        trace?: never;
    };
    "/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar todas las rutas */
        get: operations["RouteController_findAll"];
        put?: never;
        /** Crear una ruta */
        post: operations["RouteController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener una ruta por id */
        get: operations["RouteController_findOne"];
        put?: never;
        post?: never;
        /** Eliminar una ruta */
        delete: operations["RouteController_remove"];
        options?: never;
        head?: never;
        /** Actualizar parcialmente una ruta */
        patch: operations["RouteController_update"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateVehicleDto: {
            /**
             * @description Identificador interno del bus
             * @example BUS-AQP-001
             */
            code: string;
            /**
             * @description Placa peruana asignada al vehículo
             * @example ABC-123
             */
            plateNumber?: Record<string, never> | null;
            /**
             * @description Estado operativo del bus
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE" | "MAINTENANCE";
            /**
             * @description Capacidad de pasajeros
             * @example 80
             */
            capacity?: Record<string, never> | null;
            /**
             * @description Identificador de la ruta asignada
             * @example ckxyz123
             */
            routeId?: Record<string, never> | null;
        };
        VehicleResponseDto: {
            /**
             * @description Identificador único del vehículo
             * @example ckxyz123
             */
            id: string;
            /**
             * @description Identificador interno del bus
             * @example BUS-AQP-001
             */
            code: string;
            /**
             * @description Placa peruana del vehículo
             * @example ABC-123
             */
            plateNumber: Record<string, never> | null;
            /**
             * @description Estado operativo del vehículo
             * @example ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE" | "MAINTENANCE";
            /**
             * @description Capacidad de pasajeros
             * @example 80
             */
            capacity: Record<string, never> | null;
            /**
             * @description Identificador de la ruta asignada
             * @example ckxyz789
             */
            routeId: Record<string, never> | null;
            /**
             * @description Fecha de creación en formato ISO 8601
             * @example 2026-04-28T15:00:00.000Z
             */
            createdAt: string;
            /**
             * @description Fecha de última actualización en formato ISO 8601
             * @example 2026-04-28T15:00:00.000Z
             */
            updatedAt: string;
        };
        UpdateVehicleDto: {
            /**
             * @description Identificador interno del bus
             * @example BUS-AQP-001
             */
            code?: string;
            /**
             * @description Placa peruana asignada al vehículo
             * @example ABC-123
             */
            plateNumber?: Record<string, never> | null;
            /**
             * @description Estado operativo del bus
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "INACTIVE" | "MAINTENANCE";
            /**
             * @description Capacidad de pasajeros
             * @example 80
             */
            capacity?: Record<string, never> | null;
            /**
             * @description Identificador de la ruta asignada
             * @example ckxyz123
             */
            routeId?: Record<string, never> | null;
        };
        CreateRouteDto: {
            /**
             * @description Código único de la ruta
             * @example AQP-CHAR-LA
             */
            code: string;
            /**
             * @description Nombre comercial visible de la ruta
             * @example CHARACATO L A
             */
            name: string;
            /**
             * @description Descripción opcional para operaciones
             * @example Ruta urbana Characato - Linea A
             */
            description?: Record<string, never> | null;
            /**
             * @description Indica si la ruta está operativa
             * @example true
             */
            isActive?: boolean;
        };
        RouteResponseDto: {
            /**
             * @description Identificador único de la ruta
             * @example ckxyz789
             */
            id: string;
            /**
             * @description Código único de la ruta
             * @example AQP-CHAR-LA
             */
            code: string;
            /**
             * @description Nombre comercial visible de la ruta
             * @example CHARACATO L A
             */
            name: string;
            /**
             * @description Descripción de la ruta
             * @example Ruta urbana Characato - Linea A
             */
            description: Record<string, never> | null;
            /**
             * @description Indica si la ruta está operativa
             * @example true
             */
            isActive: boolean;
            /**
             * @description Fecha de creación en ISO 8601
             * @example 2026-04-28T15:00:00.000Z
             */
            createdAt: string;
            /**
             * @description Fecha de última actualización en ISO 8601
             * @example 2026-04-28T15:00:00.000Z
             */
            updatedAt: string;
        };
        UpdateRouteDto: {
            /**
             * @description Código único de la ruta
             * @example AQP-CHAR-LA
             */
            code?: string;
            /**
             * @description Nombre comercial visible de la ruta
             * @example CHARACATO L A
             */
            name?: string;
            /**
             * @description Descripción opcional para operaciones
             * @example Ruta urbana Characato - Linea A
             */
            description?: Record<string, never> | null;
            /**
             * @description Indica si la ruta está operativa
             * @example true
             */
            isActive?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    VehicleController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponseDto"][];
                };
            };
        };
    };
    VehicleController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVehicleDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponseDto"];
                };
            };
            /** @description El código o la placa ya existen */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VehicleController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del vehículo */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponseDto"];
                };
            };
            /** @description Vehículo no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VehicleController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del vehículo */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vehículo eliminado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Vehículo no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VehicleController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del vehículo */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVehicleDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleResponseDto"];
                };
            };
            /** @description Vehículo no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El código o la placa ya existen */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RouteController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponseDto"][];
                };
            };
        };
    };
    RouteController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRouteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponseDto"];
                };
            };
            /** @description El código de ruta ya existe */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RouteController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la ruta */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponseDto"];
                };
            };
            /** @description Ruta no encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RouteController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la ruta */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ruta eliminada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ruta no encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RouteController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la ruta */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRouteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteResponseDto"];
                };
            };
            /** @description Ruta no encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description El código de ruta ya existe */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
